    - name: Loop over hostnames and look up VMs
      set_fact:
        vm_hostnames: "{{ vm_hostnames | default([]) + [item.vm_name] }}"
      loop: "{{ ocpnodes_vms }}"

    - name: Look up the VM called test_vm1 in the inventory
      vmware.vmware_rest.vcenter_vm_info:
        filter_names: "{{ item.vm_name }}"
        vcenter_rest_log_file: /tmp/vmware-rest.log
      register: search_result

    - name: Check rest log
      shell: cat /tmp/vmware-rest.log

    - debug:
        var: search_result

    - name: Collect information about each VM
      vmware.vmware_rest.vcenter_vm_info:
        vm: '{{ item.vm }}'
      loop: "{{ search_result.value }}"
      register: my_vms

    - debug:
        var: my_vms      
    - name: power off VMs 
      vmware.vmware_rest.vcenter_vm_power:
        state: stop
        vm: '{{ item.vm }}'
      loop: "{{ search_result.value }}"

    - name: Attach ISO to VMs
      vmware.vmware_rest.vcenter_vm_hardware_cdrom:
        vm: '{{ item.vm }}'
        type: IDE
        start_connected: true
        allow_guest_control: true
        vcenter_rest_log_file: /tmp/log
        ide:
          primary: true
          master: true
        backing:
          iso_file: '[{{ datastore_name }}] iso/{{ ocp_cluster }}.iso'
          type: ISO_FILE
      loop: "{{ search_result.value }}"


    - name: power on the VM
      vmware.vmware_rest.vcenter_vm_power:
        state: start
        vm: '{{ item.vm }}'
      loop: "{{ search_result.value }}"
