    - name: Calculate the expected count of Agent resources
      set_fact:
        expected_count: "{{ numberof_worker + 3 }}"

    - name: Wait for the agents to become ready
      include_tasks: tasks/initialize-cluster/task-control-agent-number.yml


    - name: Get  existing agents
      k8s_info:
        api_version: agent-install.openshift.io/v1beta1
        kind: Agent
        namespace: "{{ ocp_cluster }}-deploy"
      register: all_agents
      until: all_agents.resources | length == (ocpnodes_vms | length ) + (ocpnodes_bms | length)
      retries: 180
      delay: 10


    - name: Get custom resource object names
      set_fact:
        custom_resource_names: "{{ all_agents.resources | map(attribute='metadata.name') | list }}"


    - name: Populate hostnames based on reverse DNS lookup
      set_fact:
        agent_hostnames: "{{ agent_hostnames | default({}) | combine({ item.metadata.name: (lookup('community.general.dig', ipv4_address + '/PTR') | regex_replace('\\.$', '') ) }) }}"
      with_items: "{{ all_agents.resources }}"
      vars:
        ipv4_address: >-
          {{
            item.status.inventory.interfaces |
            selectattr('name', 'in', ['ens192', 'bond0']) |
            map(attribute='ipV4Addresses') |
            first |
            default([]) |
            first |
            default('') |
            regex_replace('/.*', '')
          }}
      when: ipv4_address != ''

        
    - name: Update custom resource objects
      k8s:
        state: present
        definition: |
          apiVersion: agent-install.openshift.io/v1beta1
          kind: Agent
          metadata:
            namespace: "{{ ocp_cluster }}-deploy"
            name: "{{ item.key }}"
          spec:
            approved: true
            hostname: "{{ item.value }}"
      with_dict: "{{ agent_hostnames }}"



