apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  labels:
    cluster-name: {{ .Values.clusterName }}
  name: {{ .Values.clusterName }}
  namespace: {{ .Values.namespace_name }}
spec:
  clusterRef:
    name: {{ .Values.clusterName }}
    namespace: {{ .Values.namespace_name }}
  agentLabels:
    cluster-name: {{ .Values.clusterName }}
  cpuArchitecture: {{ .Values.cpuArchitecture | default "x86_64" }}
  nmStateConfigLabelSelector:
    matchLabels:
      cluster-name: {{ .Values.clusterName }}
  pullSecretRef:
    name: {{ .Values.pullSecretName | default (printf "pull-secret-%s" .Values.clusterName) }}
  sshAuthorizedKey: {{ .Values.sshPublicKey }}
  proxy:
    httpProxy: {{ .Values.httpProxy }}
    httpsProxy: {{ .Values.httpsProxy }}
    noProxy: {{ .Values.noProxy }}
  additionalNTPSources:
    {{- range $.Values.ntpservers }}
    - {{ . }}
    {{- end }} 
  additionalTrustBundle: |-
    -----BEGIN CERTIFICATE-----
    MIIGoDCCBYigAwIBAgITHQAAFgi6g06wlsG89QACAAAWCDANBgkqhkiG9w0BAQsF
    ADBKMRMwEQYKCZImiZPyLGQBGRYDYWtiMRUwEwYKCZImiZPyLGQBGRYFYWtuZXQx
    HDAaBgNVBAMTE2FrbmV0LVNDQ0VSU1JWWTMtQ0EwHhcNMTkwNjIxMDczMzM5WhcN
    MjMwMTI5MTQxMjI0WjBqMQswCQYDVQQGEwJUUjERMA8GA1UEBxMISXN0YW5idWwx
    FjAUBgNVBAoTDUFLQkFOSyBULkEuUy4xDzANBgNVBAsTBkFLQkFOSzEfMB0GA1UE
    AwwWKi5hcHBzLm9jcDEuYWtiYW5rLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEP
    ADCCAQoCggEBAPbD31Dqikf/ZFa1Yiq3oakl3nDg0OIlnUTWO0CyOtKQ4J5A1IGA
    0r+dfmSk3bW5yhc0pAzQjgZWgfEPCDEkc+Cyf10oj059s9+7l/EcaBfwCKPlVgf6
    a88YxNLxytceYeH9gkeur5/4YLV9aH/YPvxzC46lZmN9NEgOd+/XCg3Q/lrOolA5
    3PI3rfGvddfad9t6YlAtHxgBx511JS/WZo7FGagl82Sd6Cluw0DGaJDg/tqzdofV
    DN9wZTYkcD85hx95pSK9bvlqimRXljs3f5fwdNNiIEkMmqxfk55IXi8EiY9/pm0O
    GeDNNycgGa0CrGDjSY2HUU0TJpp/NdbXV0MCAwEAAaOCA10wggNZMD4GCSsGAQQB
    gjcVBwQxMC8GJysGAQQBgjcVCIa7vhKGmNxHhOmVLYfcjBGFkYg5gQyC1sVghb7M
    ZwIBZwIBBzAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwCwYDVR0PBAQD
    AgWgMCcGCSsGAQQBgjcVCgQaMBgwCgYIKwYBBQUHAwIwCgYIKwYBBQUHAwEwHQYD
    VR0OBBYEFDtez9SXnroRqwfcSbKCY70hmMriMDQGA1UdEQQtMCuCFiouYXBwcy5v
    Y3AxLmFrYmFuay5jb22CESoub2NwMS5ha2JhbmsuY29tMB8GA1UdIwQYMBaAFG6H
    xwh5zIz/ICSdTMIzV6ugt76KMIIBHQYDVR0fBIIBFDCCARAwggEMoIIBCKCCAQSG
    gb5sZGFwOi8vL0NOPWFrbmV0LVNDQ0VSU1JWWTMtQ0EoMSksQ049c2NjZXJzcnZ5
    MyxDTj1DRFAsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049U2VydmljZXMs
    Q049Q29uZmlndXJhdGlvbixEQz1ha25ldCxEQz1ha2I/Y2VydGlmaWNhdGVSZXZv
    Y2F0aW9uTGlzdD9iYXNlP29iamVjdENsYXNzPWNSTERpc3RyaWJ1dGlvblBvaW50
    hkFodHRwOi8vc2NjZXJzcnZ5My5ha25ldC5ha2IvQ2VydEVucm9sbC9ha25ldC1T
    Q0NFUlNSVlkzLUNBKDEpLmNybDCCASkGCCsGAQUFBwEBBIIBGzCCARcwgbAGCCsG
    AQUFBzAChoGjbGRhcDovLy9DTj1ha25ldC1TQ0NFUlNSVlkzLUNBLENOPUFJQSxD
    Tj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1
    cmF0aW9uLERDPWFrbmV0LERDPWFrYj9jQUNlcnRpZmljYXRlP2Jhc2U/b2JqZWN0
    Q2xhc3M9Y2VydGlmaWNhdGlvbkF1dGhvcml0eTBiBggrBgEFBQcwAoZWaHR0cDov
    L3NjY2Vyc3J2eTMuYWtuZXQuYWtiL0NlcnRFbnJvbGwvc2NjZXJzcnZ5My5ha25l
    dC5ha2JfYWtuZXQtU0NDRVJTUlZZMy1DQSgyKS5jcnQwDQYJKoZIhvcNAQELBQAD
    ggEBADJbqhZ3Lk0+qHwUDJ4JpmjIemYxj9sGsRW+kdBZj6AaTrt1w8H2iGjxBV54
    U6g6vn1j6QT+gxcUzfjiztzJJ6GZniuQ2bZgnqajoPNNhIewYzAVCB/j0LjwqQWI
    2+chZOM9xp85yq7RFLuD/wp/5Ik4pPUyHgdJO3RIR6D/XTjkQstZZm8EzVL9f865
    ysChV9OFa72UT4trKiHO2MzWqhiOhVUVHhbIQ8YX1a6hWRoNww4T6MaXCkK7irk0
    uOtSIlrZ20KHd8BWyHSFMo+i7BBSpPvnkc9lN6gNNI8ngaIfWBRGx0OL8NMxn7oX
    DL+OPYtiExAO8Zh64Hpe0IQ95/8=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIGjTCCBXWgAwIBAgITHQAl7lJuxVi0brNsmwACACXuUjANBgkqhkiG9w0BAQsF
    ADBKMRMwEQYKCZImiZPyLGQBGRYDYWtiMRUwEwYKCZImiZPyLGQBGRYFYWtuZXQx
    HDAaBgNVBAMTE2FrbmV0LVNDQ0VSU1JWWTMtQ0EwHhcNMjAwOTE3MDY0MTA3WhcN
    MjMwMTI5MTQxMjI0WjBqMQswCQYDVQQGEwJUUjERMA8GA1UEBxMISXN0YW5idWwx
    FjAUBgNVBAoTDUFLQkFOSyBULkEuUy4xDzANBgNVBAsTBkFLQkFOSzEfMB0GA1UE
    AwwWKi5hcHBzLm9jcDMuYWtiYW5rLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEP
    ADCCAQoCggEBAMy2pfTz8Eo56JdyudjKKz7jJhVoSLT3qMZp184qjC1TBrbqVOqM
    BCjaiAccwcUGnBGKHW+tQovyF0XNPf7Kl4pCJ//Lei+K1vz4FDLUUw8QU1D07w7m
    QrU6oazt0XAFgvGZM9M72JYCgaj7g8l5t9/yqozP9MdsmMGRMwHajT9hvoV5oaaZ
    1JJBNiHjmHkzKOKG+aXswlJF9gUATO1GUU3KDVfLIix2OviWEyI3haG1k097UuSE
    p7aFhk65Upe/mQajhIOvDFrb7G5ZRopQqmWkDSJnthJSzJqX0ptOHRIsCWxGK0d5
    pRTi6gWYyL9/bz8RUrSqlcEN96YDJux3MMcCAwEAAaOCA0owggNGMD4GCSsGAQQB
    gjcVBwQxMC8GJysGAQQBgjcVCIa7vhKGmNxHhOmVLYfcjBGFkYg5gQyC1sVghb7M
    ZwIBZwIBCTAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwCwYDVR0PBAQD
    AgWgMCcGCSsGAQQBgjcVCgQaMBgwCgYIKwYBBQUHAwIwCgYIKwYBBQUHAwEwHQYD
    VR0OBBYEFKweIDEHSvCiiy4w/0qqG4OTAg+HMCEGA1UdEQQaMBiCFiouYXBwcy5v
    Y3AzLmFrYmFuay5jb20wHwYDVR0jBBgwFoAUbofHCHnMjP8gJJ1MwjNXq6C3voow
    ggEdBgNVHR8EggEUMIIBEDCCAQygggEIoIIBBIaBvmxkYXA6Ly8vQ049YWtuZXQt
    U0NDRVJTUlZZMy1DQSgxKSxDTj1zY2NlcnNydnkzLENOPUNEUCxDTj1QdWJsaWMl
    MjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERD
    PWFrbmV0LERDPWFrYj9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0P2Jhc2U/b2Jq
    ZWN0Q2xhc3M9Y1JMRGlzdHJpYnV0aW9uUG9pbnSGQWh0dHA6Ly9zY2NlcnNydnkz
    LmFrbmV0LmFrYi9DZXJ0RW5yb2xsL2FrbmV0LVNDQ0VSU1JWWTMtQ0EoMSkuY3Js
    MIIBKQYIKwYBBQUHAQEEggEbMIIBFzCBsAYIKwYBBQUHMAKGgaNsZGFwOi8vL0NO
    PWFrbmV0LVNDQ0VSU1JWWTMtQ0EsQ049QUlBLENOPVB1YmxpYyUyMEtleSUyMFNl
    cnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9YWtuZXQsREM9
    YWtiP2NBQ2VydGlmaWNhdGU/YmFzZT9vYmplY3RDbGFzcz1jZXJ0aWZpY2F0aW9u
    QXV0aG9yaXR5MGIGCCsGAQUFBzAChlZodHRwOi8vc2NjZXJzcnZ5My5ha25ldC5h
    a2IvQ2VydEVucm9sbC9zY2NlcnNydnkzLmFrbmV0LmFrYl9ha25ldC1TQ0NFUlNS
    VlkzLUNBKDIpLmNydDANBgkqhkiG9w0BAQsFAAOCAQEAFHbNFCnuOnbx6b5Z4w9j
    9XgwQDxJHv2NiQXYS9JIi0U0QGZc0xO0h3aiFt7WOBkTk1ytyntVT07EbI5Kyoua
    yY3ZxObD1JyUxanINBCRa41rba8Hd7Q6wg0BfaDQBT/hspOnUPuoI5cn0zlcFird
    VRc+nf7ZQk3kojorgtnHj3vimiuIwMOYyDZ/FxRYrzSbAxXEO264LIdaSnA52GIU
    u59a6Rqy9fL3sAZc321sj3XfUOHSBqphkOllejnK3ZWHE93uCrRUk8LPemmk11ir
    KMvrDTkG8N4kqU3bdZUmdDMzuRtvV8f3RVx6xD/rMxUzdKf6XUlcwaIreUhXPXD8
    Xg==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFcTCCBFmgAwIBAgITfwAAAI4WoEOk4itUsAABAAAAjjANBgkqhkiG9w0BAQsF
    ADBJMRMwEQYKCZImiZPyLGQBGRYDYWtiMRUwEwYKCZImiZPyLGQBGRYFYWtuZXQx
    GzAZBgNVBAMTEkFLQkFOSy1ST09ULUNBLTI1NjAeFw0yMTA5MjMyMzE2NTFaFw0y
    NjA5MjIyMzE2NTFaMEoxEzARBgoJkiaJk/IsZAEZFgNha2IxFTATBgoJkiaJk/Is
    ZAEZFgVha25ldDEcMBoGA1UEAxMTYWtuZXQtU0NDRVJTUlZZMy1DQTCCASIwDQYJ
    KoZIhvcNAQEBBQADggEPADCCAQoCggEBALxEeqQUzelGSx123GMw1vMWvtKn4Ae0
    fDP7HZbhOcGBrZU8nu9+gsqbsDEpSg3viGPCsv0y6mXrtgcZqEZLII6WPZx95x+a
    +Jq1Gs8vqhu1iufwEwzgN4p5wbllFJDyCxmMPeN9Yxi4RrfE1LN5xHo5B+A6d7tA
    gbKkx2nGN/nTDWrgQuYSD2GXMjMYYCLyng1Tj/WFlhV0JNrZrTPEGdidtVG7EuSR
    zbFZVOvDNpCt+VDWjV8HT8l3oPN3tkGfLeGIrBf98uE3QHjO0AbYOSAvx2wQnj6A
    EDZTLD/aCnU9ufWNfjG+HK5/Y09jQuOSJs2ECsko2bQQgwzBsbnsYckCAwEAAaOC
    Ak8wggJLMBIGCSsGAQQBgjcVAQQFAgMBAAMwIwYJKwYBBAGCNxUCBBYEFL6g0tH5
    Daqt9h0Fji5Zhf6SoVPyMB0GA1UdDgQWBBRuh8cIecyM/yAknUzCM1eroLe+ijAZ
    BgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/
    BAUwAwEB/zAfBgNVHSMEGDAWgBRUGKtZC2evVaKH07ucpfVkH0mLvzCB0QYDVR0f
    BIHJMIHGMIHDoIHAoIG9hoG6bGRhcDovLy9DTj1BS0JBTkstUk9PVC1DQS0yNTYs
    Q049c2NjZXJzcnZ5MSxDTj1DRFAsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMs
    Q049U2VydmljZXMsQ049Q29uZmlndXJhdGlvbixEQz1ha25ldCxEQz1ha2I/Y2Vy
    dGlmaWNhdGVSZXZvY2F0aW9uTGlzdD9iYXNlP29iamVjdENsYXNzPWNSTERpc3Ry
    aWJ1dGlvblBvaW50MIHCBggrBgEFBQcBAQSBtTCBsjCBrwYIKwYBBQUHMAKGgaJs
    ZGFwOi8vL0NOPUFLQkFOSy1ST09ULUNBLTI1NixDTj1BSUEsQ049UHVibGljJTIw
    S2V5JTIwU2VydmljZXMsQ049U2VydmljZXMsQ049Q29uZmlndXJhdGlvbixEQz1h
    a25ldCxEQz1ha2I/Y0FDZXJ0aWZpY2F0ZT9iYXNlP29iamVjdENsYXNzPWNlcnRp
    ZmljYXRpb25BdXRob3JpdHkwDQYJKoZIhvcNAQELBQADggEBAEG634b0l3nImFLR
    iMF3tWSn9KNTwe8O7WM4zetlKXfLW4CyJ099w/aCa21BAP3md5aXopV2f/nAdBKR
    YvJhU7KWIq/oIUyWf0MwFc3B+3C8opJNDV59VLkzJViGPnCYJZr7yJz2ycTasoJG
    6FIHlMH0bOEW+Ki5rAAeziVxEwe1O8pmG52KCOrE4oj97imRZEx4CLEF8OA3YuEE
    nlCHv61TTlCYsSHNJyitGMs5V11qcN5eqWSxWYCFb8xk4K9p1L8hwKT+gpORG9/y
    +OIJa1Vx3Jj8zDAOb/gGJaMOsiTcrYK/a8aVm539U5evpBU2/cTlXLNfL1ww4ngN
    rlAj8dQ=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDqzCCApOgAwIBAgIQL73acP7gcKlEk839xmM2CTANBgkqhkiG9w0BAQsFADBJ
    MRMwEQYKCZImiZPyLGQBGRYDYWtiMRUwEwYKCZImiZPyLGQBGRYFYWtuZXQxGzAZ
    BgNVBAMTEkFLQkFOSy1ST09ULUNBLTI1NjAgFw0xNTA2MDMwODQ0MTlaGA8yMDYx
    MDkyMzIwNDI1OFowSTETMBEGCgmSJomT8ixkARkWA2FrYjEVMBMGCgmSJomT8ixk
    ARkWBWFrbmV0MRswGQYDVQQDExJBS0JBTkstUk9PVC1DQS0yNTYwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCuE0zJQpcW+kuW4rnMyYqBsVjNb56WaN1G
    MlCPHsAfvD61/vldrIi7w+DAHP9BszQfRgPV8ddHTtsuVbVuJNIA5X6jWCm9CUl6
    qwCxHh/aLa7G5XCBJ8M2s6Bo8/LVB9d44OVtxbKwNVbuoIIlU1XnJZclcQmLGvsl
    FvRmrcN92+y19wJrtaX9Oau8XVMSLyY8rLgrbuY4DCKpk+Vi37vcBZloCxDOVMaQ
    mv2gMTbUxIiaZhFKsTV8NezvWVFySjSc4joBzlrg4h5Qws+tNGaPh8EYX2mY5g85
    w3u0s7ljaFfRx5xH/H4XIlOhS9LNpMwQdPeloD5zjpK5ABspsZg9AgMBAAGjgYww
    gYkwEwYJKwYBBAGCNxQCBAYeBABDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQF
    MAMBAf8wHQYDVR0OBBYEFFQYq1kLZ69VoofTu5yl9WQfSYu/MBAGCSsGAQQBgjcV
    AQQDAgEBMCMGCSsGAQQBgjcVAgQWBBRiPKRtIYz2rDJN4yhfM1IsGM+nVzANBgkq
    hkiG9w0BAQsFAAOCAQEADMtNVD4Vyml8ZgbNq6dmphQJBRji1DbYotQeIABJMpQP
    La+zCBFNNsQ6QgmF3YR65Ug5xrDDqyilRnGyopMCftsyhumlXFCRMSsvq6y1L8nt
    oI9q5TraArhaBACzYzPTVtg3JsFlgqeIV0GJknUrASeFWdJaxorNCE7kVNkmN7Y+
    RuY04o5Xaqe/4E4YVkhfeOMNRipkQ7xpmUBXC51CXfY4kkCJK/qpK3mtNpoojG4u
    v7n/s20b49GG5qdE4jYVtzR+7AWiK5p2t6JBFG5+1YGQWIMS1LBMZMZzKNFIerMG
    YpDYxElJgeaKR09aIIzmWLFcSbidkIHF438YjBqyhA==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDgjCCAmqgAwIBAgIQevl2GLBaiJZPaOaqOhF2RzANBgkqhkiG9w0BAQsFADBJ
    MRMwEQYKCZImiZPyLGQBGRYDYWtiMRUwEwYKCZImiZPyLGQBGRYFYWtuZXQxGzAZ
    BgNVBAMTEkFLQkFOSy1ST09ULUNBLTI1NjAeFw0xNTA2MDMwODQ0MTlaFw0yNTA2
    MDMwODU0MThaMEkxEzARBgoJkiaJk/IsZAEZFgNha2IxFTATBgoJkiaJk/IsZAEZ
    FgVha25ldDEbMBkGA1UEAxMSQUtCQU5LLVJPT1QtQ0EtMjU2MIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEArhNMyUKXFvpLluK5zMmKgbFYzW+elmjdRjJQ
    jx7AH7w+tf75XayIu8PgwBz/QbM0H0YD1fHXR07bLlW1biTSAOV+o1gpvQlJeqsA
    sR4f2i2uxuVwgSfDNrOgaPPy1QfXeODlbcWysDVW7qCCJVNV5yWXJXEJixr7JRb0
    Zq3DfdvstfcCa7Wl/TmrvF1TEi8mPKy4K27mOAwiqZPlYt+73AWZaAsQzlTGkJr9
    oDE21MSImmYRSrE1fDXs71lRcko0nOI6Ac5a4OIeUMLPrTRmj4fBGF9pmOYPOcN7
    tLO5Y2hX0cecR/x+FyJToUvSzaTMEHT3paA+c46SuQAbKbGYPQIDAQABo2YwZDAT
    BgkrBgEEAYI3FAIEBh4EAEMAQTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB
    /zAdBgNVHQ4EFgQUVBirWQtnr1Wih9O7nKX1ZB9Ji78wEAYJKwYBBAGCNxUBBAMC
    AQAwDQYJKoZIhvcNAQELBQADggEBAKhcLaaQdgWBra0kLAXxziN49xAWJxotejx5
    sTb242jxuW+7zGILtZJWvMP126gVytPszt8t1XXfxbvLDSn9gja++HpMLZQt8D0A
    GEkDAMb1wQWfaQBz3dhf4e9bqFah3N/AJkrwmw+6378wGFPuAzQsmN9t3v+PacPn
    rqw+nigWxdWkbO+mT27+tMiYiPCbWv72FI7qrZmmJ80IbO1GbKxGqi/LQo0UY9Oc
    jL6+yzmEu7DYuHXa+UpuyPwWJcT+iRo9uCHFogadE6NyA6g7QNfXBmTVZUjLxwFP
    //NPSMGQCV022nkC108Aa43tXSRPcXakVM5BSL7GkCdnlDJ+Tfs=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFcTCCBFmgAwIBAgITfwAAAF+d4HA8q57+lgAAAAAAXzANBgkqhkiG9w0BAQsF
    ADBJMRMwEQYKCZImiZPyLGQBGRYDYWtiMRUwEwYKCZImiZPyLGQBGRYFYWtuZXQx
    GzAZBgNVBAMTEkFLQkFOSy1ST09ULUNBLTI1NjAeFw0xODAxMzAxNDEyMjRaFw0y
    MzAxMjkxNDEyMjRaMEoxEzARBgoJkiaJk/IsZAEZFgNha2IxFTATBgoJkiaJk/Is
    ZAEZFgVha25ldDEcMBoGA1UEAxMTYWtuZXQtU0NDRVJTUlZZMy1DQTCCASIwDQYJ
    KoZIhvcNAQEBBQADggEPADCCAQoCggEBALxEeqQUzelGSx123GMw1vMWvtKn4Ae0
    fDP7HZbhOcGBrZU8nu9+gsqbsDEpSg3viGPCsv0y6mXrtgcZqEZLII6WPZx95x+a
    +Jq1Gs8vqhu1iufwEwzgN4p5wbllFJDyCxmMPeN9Yxi4RrfE1LN5xHo5B+A6d7tA
    gbKkx2nGN/nTDWrgQuYSD2GXMjMYYCLyng1Tj/WFlhV0JNrZrTPEGdidtVG7EuSR
    zbFZVOvDNpCt+VDWjV8HT8l3oPN3tkGfLeGIrBf98uE3QHjO0AbYOSAvx2wQnj6A
    EDZTLD/aCnU9ufWNfjG+HK5/Y09jQuOSJs2ECsko2bQQgwzBsbnsYckCAwEAAaOC
    Ak8wggJLMBIGCSsGAQQBgjcVAQQFAgMBAAIwIwYJKwYBBAGCNxUCBBYEFKx1/dPt
    UTiwJ5DPO3/j1w02OgLNMB0GA1UdDgQWBBRuh8cIecyM/yAknUzCM1eroLe+ijAZ
    BgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/
    BAUwAwEB/zAfBgNVHSMEGDAWgBRUGKtZC2evVaKH07ucpfVkH0mLvzCB0QYDVR0f
    BIHJMIHGMIHDoIHAoIG9hoG6bGRhcDovLy9DTj1BS0JBTkstUk9PVC1DQS0yNTYs
    Q049c2NjZXJzcnZ5MSxDTj1DRFAsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMs
    Q049U2VydmljZXMsQ049Q29uZmlndXJhdGlvbixEQz1ha25ldCxEQz1ha2I/Y2Vy
    dGlmaWNhdGVSZXZvY2F0aW9uTGlzdD9iYXNlP29iamVjdENsYXNzPWNSTERpc3Ry
    aWJ1dGlvblBvaW50MIHCBggrBgEFBQcBAQSBtTCBsjCBrwYIKwYBBQUHMAKGgaJs
    ZGFwOi8vL0NOPUFLQkFOSy1ST09ULUNBLTI1NixDTj1BSUEsQ049UHVibGljJTIw
    S2V5JTIwU2VydmljZXMsQ049U2VydmljZXMsQ049Q29uZmlndXJhdGlvbixEQz1h
    a25ldCxEQz1ha2I/Y0FDZXJ0aWZpY2F0ZT9iYXNlP29iamVjdENsYXNzPWNlcnRp
    ZmljYXRpb25BdXRob3JpdHkwDQYJKoZIhvcNAQELBQADggEBAExGSzXlm6oDDOEi
    xm+E0iiPFNrB15VPMGyGDXeDCNKMZwQPzhAxdAiCVxtOKz/JBEsY4Zan4UsLh78I
    TwtpqWFiyuFxI9j1T/uhCNC4BRzEI7pAnFrthYfGagPYY/XUgDpgEcvYKzt27eD4
    4Ybo4QOumLX4wGJ4y9FWtYGtsNm3Y88g3H9vlDtEEnLTxho5yfuiQsP6avIUlv1y
    6HpfpMqBVpbTNVu8odAdhnfLhseaz8lMC2njDXAVMD82Fns6t07IGrBcK1J9E4o7
    56akYVu2iyKjION5x/q/8Bb110eRg1dn/dSY9jIYlVh0TakcajJFTbxvRA5keEd0
    ZJnqmNE=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFdTCCBF2gAwIBAgITfwAAAGKjsyd9+mg0ygAAAAAAYjANBgkqhkiG9w0BAQsF
    ADBJMRMwEQYKCZImiZPyLGQBGRYDYWtiMRUwEwYKCZImiZPyLGQBGRYFYWtuZXQx
    GzAZBgNVBAMTEkFLQkFOSy1ST09ULUNBLTI1NjAeFw0xODAxMzAxNDM2MzVaFw0y
    MzAxMjkxNDM2MzVaME4xEzARBgoJkiaJk/IsZAEZFgNha2IxFTATBgoJkiaJk/Is
    ZAEZFgVha25ldDEgMB4GA1UEAxMXQUtCQU5LIFNFUlRJRklLQSBTSEEyNTYwggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDeAmtvDAFMriEccw8R6mmMCHte
    JQgVfVdl6x9uoUQrgorktFHl+0k9iCuZrEOdqFM9dxR0lPC71ZH41vn61F2azBb8
    PyWtPgbr7dF/QzMV275Z9qy0Uvhp4pCqqaAPYrNUKUuCU2IyIbk7Y7ghIJiK+6bX
    2UkTmh8wDBkjwUCsUwO1vq+6lvEZ6iKXuSrWZhn6m7qcnlNrEO+HgK9FP3GtlnD2
    s5C1hk1b3AxOYzix3pGhMarOo32UOp7h53ul2tPBqDbDaMTNq8FFRCSSB7TvMXT0
    z4yA0JFgvXXR99w7PvR/O3ZUlDB1RB3DDdh4ZNs+zN05d7D5EmLKfc1whoexAgMB
    AAGjggJPMIICSzASBgkrBgEEAYI3FQEEBQIDAQADMCMGCSsGAQQBgjcVAgQWBBSw
    nQjLnsbM+P0kaOD6od27XLyuLjAdBgNVHQ4EFgQUql+hP9ZpVeCI/nW09D/5RA6W
    i28wGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1Ud
    EwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAUVBirWQtnr1Wih9O7nKX1ZB9Ji78wgdEG
    A1UdHwSByTCBxjCBw6CBwKCBvYaBumxkYXA6Ly8vQ049QUtCQU5LLVJPT1QtQ0Et
    MjU2LENOPXNjY2Vyc3J2eTEsQ049Q0RQLENOPVB1YmxpYyUyMEtleSUyMFNlcnZp
    Y2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9YWtuZXQsREM9YWti
    P2NlcnRpZmljYXRlUmV2b2NhdGlvbkxpc3Q/YmFzZT9vYmplY3RDbGFzcz1jUkxE
    aXN0cmlidXRpb25Qb2ludDCBwgYIKwYBBQUHAQEEgbUwgbIwga8GCCsGAQUFBzAC
    hoGibGRhcDovLy9DTj1BS0JBTkstUk9PVC1DQS0yNTYsQ049QUlBLENOPVB1Ymxp
    YyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24s
    REM9YWtuZXQsREM9YWtiP2NBQ2VydGlmaWNhdGU/YmFzZT9vYmplY3RDbGFzcz1j
    ZXJ0aWZpY2F0aW9uQXV0aG9yaXR5MA0GCSqGSIb3DQEBCwUAA4IBAQBlAgRS5nQz
    YG+bWG0oOaQ7eMBmcrPzYOfyaFC96EQJfJ7jsK9hKViFNU62JxMk1CZljYXXodZV
    NiyjPnI6PQKLOfY9WDdXdC8H7tr+/+zF7r7jvK+UyNXWHCQbtTO3Wpg0oW3AdG8y
    EAE6RROBn8fdh0TtV13xE6ONsw31yeVnm7Oqa0ArZgCnHPI4Ui1IwHz5CU7qvo4X
    VZAJ6if5OV9A+VyJ6E0fYWMphUFRZKr2x37D4jaN4qc9I5RubG9TDXAMqrAa7bPL
    J3mzzPE2UNsUWVe5vTaxllV+zaV60IeWDnuSzcYkHNsXfGIv1QqOzLzfUh+kOW4X
    UjRjNh3+5dSm
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIEBDCCAuygAwIBAgIQI5TbcFpLxZFJimVS3gBziTANBgkqhkiG9w0BAQsFADBU
    MQswCQYDVQQGEwJUUjEWMBQGA1UECgwNQWtiYW5rIFQuQS5TLjEtMCsGA1UEAwwk
    QUtCQU5LIElOVEVSTkVUIEdVVkVOTElLIFNFUlRJRklLQVNJMB4XDTE2MDIxOTA3
    NDYwN1oXDTM2MDIxNDA3NDYwN1owVDELMAkGA1UEBhMCVFIxFjAUBgNVBAoMDUFr
    YmFuayBULkEuUy4xLTArBgNVBAMMJEFLQkFOSyBJTlRFUk5FVCBHVVZFTkxJSyBT
    RVJUSUZJS0FTSTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJckoeix
    +26ehTG0Sa8L5YX1yIb75uCPvvh3p1ThbgS+RJUJFcqALh84eKLgFbY6ddaVp30V
    ayuI+yGGBIERX06SXe3rdo+zyJFpELGSBwOlc78+wNwkZEKRG81rduclpNXlJXZb
    Rjw7jVLfgKGjGXvQ+1iMm1KmL5wpsAyLU9r62lcpOhhMeeNTNQPzzpBMpqVGJI0A
    NfLnSlauJgqSC+w4EEuTSxX2/9eXfB/0PZ1bRZTtsaAr/L1s6s65drA9VA5QJiWh
    Bcwij2YwpJ+emAXewrAucauY6oqmBi6M+sAAULm+bOiH+sWW4hjo5u+NJBxOsQ28
    haZX7/mVrT+WLHcCAwEAAaOB0TCBzjAMBgNVHRMEBTADAQH/MB0GA1UdDgQWBBTY
    nUFupPzN2UlZkyNZzdrxOqpHMDCBjQYDVR0jBIGFMIGCgBTYnUFupPzN2UlZkyNZ
    zdrxOqpHMKFYpFYwVDELMAkGA1UEBhMCVFIxFjAUBgNVBAoMDUFrYmFuayBULkEu
    Uy4xLTArBgNVBAMMJEFLQkFOSyBJTlRFUk5FVCBHVVZFTkxJSyBTRVJUSUZJS0FT
    SYIQI5TbcFpLxZFJimVS3gBziTAPBglghkgBhvhCAQ0EAhYAMA0GCSqGSIb3DQEB
    CwUAA4IBAQASWubOnENIJRoLdv6RSLhjriRZMTOie9ANgtJaCX8PoyQZlTYbF2j0
    lKb8FpJyfZwClaXfEhCCqpHdcctTcK/Z1ac9uzpyNpoqUsEF2vKYKAbXr3GT9ZEz
    3ZOUMcnMMUGXtPiRXquBemBbJinVJoSqm/1Uk2yqUwyRysDC54DnazUkjNbuMkjH
    hcQAHX1UcQRuQa4mEKFrRLD5gBitrz1yGG6AIFecJaUIjidd8jGsovnzd7hctyBp
    HXoZfFMfqmCihFnanad8xOH1BsQuUV9siF672jA7pWv6MkZ6kEL2vT5T3EHZJ6sL
    mLH8sHMQMNnl9K4Cl0LJcmICAEETl+ij
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFljCCBH6gAwIBAgITfwAAAJLtqLMQ1k4BhAABAAAAkjANBgkqhkiG9w0BAQsF
    ADBJMRMwEQYKCZImiZPyLGQBGRYDYWtiMRUwEwYKCZImiZPyLGQBGRYFYWtuZXQx
    GzAZBgNVBAMTEkFLQkFOSy1ST09ULUNBLTI1NjAeFw0yMTEwMjExOTQzMTZaFw00
    MTEwMTYxOTQzMTZaMEoxEzARBgoJkiaJk/IsZAEZFgNha2IxFTATBgoJkiaJk/Is
    ZAEZFgVha25ldDEcMBoGA1UEAxMTYWtuZXQtU0NDRVJTUlZZMy1DQTCCASIwDQYJ
    KoZIhvcNAQEBBQADggEPADCCAQoCggEBALxEeqQUzelGSx123GMw1vMWvtKn4Ae0
    fDP7HZbhOcGBrZU8nu9+gsqbsDEpSg3viGPCsv0y6mXrtgcZqEZLII6WPZx95x+a
    +Jq1Gs8vqhu1iufwEwzgN4p5wbllFJDyCxmMPeN9Yxi4RrfE1LN5xHo5B+A6d7tA
    gbKkx2nGN/nTDWrgQuYSD2GXMjMYYCLyng1Tj/WFlhV0JNrZrTPEGdidtVG7EuSR
    zbFZVOvDNpCt+VDWjV8HT8l3oPN3tkGfLeGIrBf98uE3QHjO0AbYOSAvx2wQnj6A
    EDZTLD/aCnU9ufWNfjG+HK5/Y09jQuOSJs2ECsko2bQQgwzBsbnsYckCAwEAAaOC
    AnQwggJwMBIGCSsGAQQBgjcVAQQFAgMBAAQwIwYJKwYBBAGCNxUCBBYEFHgJZoX3
    IgID4R7wYepPbetVlg0KMB0GA1UdDgQWBBRuh8cIecyM/yAknUzCM1eroLe+ijA+
    BgkrBgEEAYI3FQcEMTAvBicrBgEEAYI3FQiGu74ShpjcR4TplS2H3IwRhZGIOYEM
    ge2vSYX4pXoCAWQCAQMwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYD
    VR0jBBgwFoAUVBirWQtnr1Wih9O7nKX1ZB9Ji78wgdEGA1UdHwSByTCBxjCBw6CB
    wKCBvYaBumxkYXA6Ly8vQ049QUtCQU5LLVJPT1QtQ0EtMjU2LENOPXNjY2Vyc3J2
    eTEsQ049Q0RQLENOPVB1YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2Vz
    LENOPUNvbmZpZ3VyYXRpb24sREM9YWtuZXQsREM9YWtiP2NlcnRpZmljYXRlUmV2
    b2NhdGlvbkxpc3Q/YmFzZT9vYmplY3RDbGFzcz1jUkxEaXN0cmlidXRpb25Qb2lu
    dDCBwgYIKwYBBQUHAQEEgbUwgbIwga8GCCsGAQUFBzAChoGibGRhcDovLy9DTj1B
    S0JBTkstUk9PVC1DQS0yNTYsQ049QUlBLENOPVB1YmxpYyUyMEtleSUyMFNlcnZp
    Y2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9YWtuZXQsREM9YWti
    P2NBQ2VydGlmaWNhdGU/YmFzZT9vYmplY3RDbGFzcz1jZXJ0aWZpY2F0aW9uQXV0
    aG9yaXR5MA0GCSqGSIb3DQEBCwUAA4IBAQBaSC5vnAFm7/yy95KzwnsfT78EHeVG
    6TuRPRt4XuWb+lNS52bCuqRjeRNavW5inVzkuj2y6L6tixIJwMKU5h0Y3hK3Mn1N
    YAUVRWBpvax2nIPlY4OEXafYzajUj5gSrau5t9HB8794xaUTboAjwUXIaPJXn3e/
    Pnt7fTXKmYLAD5phHFevNFq2YwiqtMNLpBQl5ShGAI/Qjik0AB1vZsD5qClhkwmy
    lTB0Uv/kQrdjUIJsQv6ZKieIloVbm/UzDf95UnxdZ82NffOVfdpggMT3nlOTlR3/
    IqU+PC+RCITvu3JgnXE+R3Cgdo5L8DXAK5N+rPm9Z3LvgI0hAgv9PiCX
    -----END CERTIFICATE-----
