kind: ConfigMap
apiVersion: v1
metadata:
  name: router-configuration
  namespace: {{ $.Values.namespace_name }}
data:
  99_router-config.yaml: |
    apiVersion: operator.openshift.io/v1
    kind: IngressController
    metadata:
      name: default
      namespace: openshift-ingress-operator
    spec:
      nodePlacement:
        nodeSelector:
          matchLabels:
            node-role.kubernetes.io/router: ""
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/router
          value: reserved
        - effect: NoExecute
          key: node-role.kubernetes.io/router
          value: reserved
      replicas: 3
      httpEmptyRequestsPolicy: Respond
      tlsSecurityProfile:
        custom:
          ciphers:
          - TLS_AES_128_GCM_SHA256
          - TLS_AES_256_GCM_SHA384
          - TLS_CHACHA20_POLY1305_SHA256
          - ECDHE-ECDSA-AES128-GCM-SHA256
          - ECDHE-RSA-AES128-GCM-SHA256
          - ECDHE-ECDSA-AES256-GCM-SHA384
          - ECDHE-RSA-AES256-GCM-SHA384
          - ECDHE-ECDSA-CHACHA20-POLY1305
          - ECDHE-RSA-CHACHA20-POLY1305
          - DHE-RSA-AES128-GCM-SHA256
          - DHE-RSA-AES256-GCM-SHA384
          - ECDHE-RSA-AES128-SHA256
          - AES256-SHA
          minTLSVersion: VersionTLS12
        type: Custom
