apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pullSecretName | default (printf "pull-secret-%s" .Values.clusterName) }}
  namespace: {{ .Values.namespace_name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Files.Get .Values.pullSecret | b64enc | quote }}
